/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wairdell_learnhelp_bridge_SaFormater */

#ifndef _Included_com_wairdell_learnhelp_bridge_SaFormater
#define _Included_com_wairdell_learnhelp_bridge_SaFormater
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wairdell_learnhelp_bridge_SaFormater
 * Method:    format
 * Signature: (Ljava/util/Map;)V
 */
JNIEXPORT void JNICALL Java_com_wairdell_learnhelp_bridge_SaFormater_format
  (JNIEnv *, jobject, jobject);

JNIEXPORT void JNICALL Java_com_wairdell_learnhelp_bridge_SaFormater_verify(JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
